### ISSUE TITLE
Fix migrations

### ISSUE THREAD

**Issue by mist-webit** [nevmerzhitsky/yii2-seomodule#1]
Please, fix migrations:
- m151117_000000_create_meta_table.php line 18 **->default(0)** errors,  ->defaultValue(0) works
- m151117_000001_create_redirect_table.php wrong table name, **seo_redirec**, in createTable 

Thank You!

**Comment by nevmerzhitsky** [comment]
Thank for report! I fix it. But in current version this tables does not used. :(
